plugins {
    id 'application'
}

group = 'de.horizon'
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.javalin:javalin:6.7.0'
    implementation 'org.slf4j:slf4j-simple:2.0.17'
    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'io.github.canary-prism:querz-nbt:6.2.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'de.horizon.backend.HorizonBackendApplication'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
